version: '3'
services:
    web:
        build: .
        volumes:
          - .:/app
        ports:
          - "8000:8000"
        depends_on:
          - postgres
    postgres:
        build: docker/postgres
        ports:
          - "5432:5432"
        environment:
          POSTGRES_USER: ueda
          POSTGRES_PASSWORD: hikaru
          POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
          PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
           - ./docker/postgres/data/:/var/lib/postgresql/data/
        user: root
        tty: true
        restart: always
    cron:
        build: docker/cron
        volumes:
           - ./src/cron/:/src/
