version: '3'
services:
    web:
        build: docker/web
        volumes:
          - ./src/app:/app
        environment:
          PGHOST: postgres
          PGPORT: ${POSTGRES_PORT}
          PGUSER: ${POSTGRES_USER}
          PGPASSWORD: ${POSTGRES_PASSWORD}
        ports:
          - "3031:3031"
        depends_on:
          - postgres
    web-nginx:
        build: docker/web-nginx
        volumes:
          - ./docker/web-nginx/nginx.conf:/etc/nginx/nginx.conf
        links:
          - web
        ports:
          - "4231:80"
    api-sanic:
        build: docker/api
        volumes:
          - ./src/api:/api
        environment:
          PGHOST: postgres
          PGPORT: ${POSTGRES_PORT}
          PGUSER: ${POSTGRES_USER}
          PGPASSWORD: ${POSTGRES_PASSWORD}
        ports:
          - "3032:3032"
        depends_on:
          - postgres
    postgres:
        build: docker/postgres
        ports:
          - "5432:${POSTGRES_PORT}"
        environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
          PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
           - ./docker/postgres/data/:/var/lib/postgresql/data/
        user: root
        tty: true
        restart: always
    cron:
        build: docker/cron
        environment:
          PGHOST: postgres
          PGPORT: ${POSTGRES_PORT}
          PGUSER: ${POSTGRES_USER}
          PGPASSWORD: ${POSTGRES_PASSWORD}
        depends_on:
          - postgres
        volumes:
           - ./src/:/src/
           - ./log/:/log/
    https-portal:
        image: steveltn/https-portal:latest
        ports:
          - '80:80'
          - '443:443'
        links:
          - web-nginx
        restart: always
        environment:
          DOMAINS: 'uedahikaru.info -> http://web-nginx/'
          STAGE: local
          #STAGE: 'production'
        volumes:
          - ./docker/https/certs/:/var/lib/https-portal/
