version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.6.5
    steps:
      - checkout
      - run:
            name: docker-compose build
            command: docker-compose build
      - run:
            name: docker-compose up
            command: docker-compose up -d
      - run:
            name: run flake8
            command: docker-compose run web flake8  --show-source src/*
