version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
            name: docker-compose build
            command: docker-compose build
      - run:
            name: docker-compose up
            command: docker-compose up -d
