version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.6.5
    steps:
      - checkout
      - run:
            name: pip upgrade
            command: pip install --upgrade pip
      - run:
            name: pip install
            command: sudo pip install -r requirements-dev.txt
      - run:
            name: run flake8
            command: flake8  --show-source src/*
