version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
            name: docker-compose build
            command: docker-compose build
      - run:
            name: docker-compose up
            command: docker-compose up -d
      - run:
            name: pip install
            command: pip install flake8
      - run:
            name: run flake8
            command: flake8  --show-source src/*
