version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
            name: docker-compose build postgres
            command: docker-compose build postgres
      - run:
            name: docker-compose build cron
            command: docker-compose build cron
      - run:
            name: docker-compose build web
            command: docker-compose build web            
      - run:
            name: docker-compose up
            command: docker-compose up -d
      - run:
            name: run flake8
            command: docker-compose run web flake8  --show-source src/*
