version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.6.5
    steps: ~/repo
      - checkout
      - run:
            name: pip upgrade
            comaand: pip install --upgrade pip
      - run:
            name: pip install
            command: pip install -r requirements-dev.txt
      - run:
            name: run flake8
            command: flake8  --show-source src/*
