version: 2
jobs:
  dockertest:
    machine: true
    steps:
      - checkout
      - run:
            name: Copy env
            command: cp .env.sample .env
      - run:
            name: docker-compose build postgres
            command: docker-compose build postgres
      - run:
            name: docker-compose build cron
            command: docker-compose build cron
      - run:
            name: docker-compose build web
            command: docker-compose build web
      - run:
            name: docker-compose build web-nginx
            command: docker-compose build web-nginx
      - run:
            name: docker-compose up
            command: docker-compose up -d
  pythontest:
    machine: true
    steps:
      - checkout
      - run:
            name: run flake8
            command: docker-compose run web flake8  --show-source src/*
workflows:
  version: 2
  test:
    jobs:
      - docker test
      - python test
