proxy:
    build: docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    restart: always
    tty: true
    environment:
      DEFAULT_HOST: uedahikaru.test
    networks:
